import os
from dotenv import load_dotenv

load_dotenv()


def generate_document(document_type, parties, terms, dates):
    """
    Generate a basic legal document draft.
    """

    document = f"""
LEGAL DOCUMENT
==============

Document Type:
{document_type}

Parties:
{parties}

Effective Date:
{dates}

Terms and Conditions:
{terms}

Generated by:
LegalEase

DISCLAIMER:
This document is generated for educational and drafting purposes.
It should be reviewed by a qualified legal professional before use.
"""

    return document.strip()
